# Generated by Django 4.2.4 on 2023-08-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="")),
                ("caption", models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("address", models.CharField(max_length=140)),
                ("price", models.IntegerField(help_text="USD per night")),
                ("beds", models.IntegerField(default=1)),
                ("bedrooms", models.IntegerField(default=1)),
                ("bathrooms", models.IntegerField(default=1)),
                ("check_in", models.TimeField(default="00:00:00")),
                ("check_out", models.TimeField(default="00:00:00")),
                ("instant_book", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
